on : push
jobs : 
    first_job :
        runs-on : windows-latest 
        steps : 
            - uses : actions/checkout@v3
            - run : npx eslint index.js
            - run : node index.js

            
